import FontAwesome from "@expo/vector-icons/FontAwesome";
import { BeVietnamPro_400Regular } from "@expo-google-fonts/be-vietnam-pro/400Regular";
import { BeVietnamPro_600SemiBold } from "@expo-google-fonts/be-vietnam-pro/600SemiBold";
import { useFonts } from "@expo-google-fonts/be-vietnam-pro/useFonts";
import { useEffect, useMemo, useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { getDeviceId } from "@/auth/device";
import { createConfiguredAuthGateway, GatewayError, type GatewayErrorCode } from "@/auth/gateway";
import { createMockAuthGateway } from "@/auth/mockGateway";
import { useAuth } from "@/auth/AuthProvider";
import { FONT_STARTUP_TIMEOUT_MS, getFontStartupDiagnostic, getFontStartupState } from "@/startup/fontState";
import { normalizeEmail, validateEmail, validatePassword } from "@/auth/validation";
import { getRecoveryReviewStep } from "@/auth/recoveryReview";
import { ForgotPasswordScreen } from "@/screens/ForgotPasswordScreen";

type Screen = "signIn" | "signUpEmail" | "signUpOtp" | "signUpPassword" | "forgotPassword";
const errors: Record<GatewayErrorCode, string> = { INVALID_CREDENTIALS: "Email hoặc mật khẩu không đúng.", ACCOUNT_UNVERIFIED: "Email này chưa được xác thực. Hãy kiểm tra mã OTP.", ACCOUNT_INACTIVE: "Tài khoản hiện không hoạt động.", OTP_EXPIRED: "Mã đã hết hạn. Hãy gửi lại mã mới.", OTP_ATTEMPTS_EXHAUSTED: "Bạn đã nhập sai quá nhiều lần. Hãy gửi lại mã.", RESEND_COOLDOWN: "Vui lòng chờ trước khi gửi lại mã.", RESEND_LIMIT: "Bạn đã đạt giới hạn gửi mã trong một giờ.", INVALID_OTP: "Mã xác thực không đúng.", ACCOUNT_EXISTS: "Tài khoản đã tồn tại. Hãy đăng nhập để tiếp tục.", AUTH_RATE_LIMITED: "Bạn đã thao tác quá nhiều. Vui lòng thử lại sau.", OTP_PROVIDER_UNAVAILABLE: "Dịch vụ gửi mã đang bận. Vui lòng thử lại sau.", SIGNUP_UNAVAILABLE: "Đăng ký hiện chưa khả dụng. Vui lòng thử lại sau.", PASSWORD_RECOVERY_OTP_INVALID: "Mã xác thực không đúng hoặc đã hết hạn.", PASSWORD_RESET_TOKEN_INVALID: "Phiên khôi phục đã hết hạn. Vui lòng bắt đầu lại.", PASSWORD_CONFIRMATION_MISMATCH: "Xác nhận mật khẩu chưa khớp.", PASSWORD_UNCHANGED: "Mật khẩu mới phải khác mật khẩu hiện tại.", INVALID_SESSION: "Phiên đăng nhập đã hết hạn.", NETWORK_ERROR: "Không thể kết nối máy chủ. Vui lòng thử lại.", SERVER_WAKING: "Máy chủ đang khởi động. Vui lòng thử lại sau ít phút.", SERVER_ERROR: "Máy chủ đang gặp sự cố. Vui lòng thử lại sau.", CONFIGURATION_ERROR: "Ứng dụng chưa được cấu hình kết nối máy chủ." };
const message = (cause: unknown, fallback: string) => cause instanceof GatewayError ? errors[cause.code] : fallback;
const maskedEmail = (email: string) => { const [name = "", domain = ""] = email.split("@"); return `${name.slice(0, 2)}***@${domain}`; };
const showSocials = process.env.EXPO_PUBLIC_REVIEW_SOCIALS === "true";
const showRecoveryReview = process.env.EXPO_PUBLIC_UC03_REVIEW === "true";
const isDebugBuild = process.env.EXPO_PUBLIC_DEBUG_REVISION === "true";

export function AuthScreen() {
  const recoveryReviewStep = useMemo(getRecoveryReviewStep, []);
  const [fontsLoaded, fontError] = useFonts({ BeVietnamPro_400Regular, BeVietnamPro_600SemiBold });
  const [fontTimedOut, setFontTimedOut] = useState(false);
  const { signIn } = useAuth();
  const { width, height } = useWindowDimensions(); const gateway = useMemo(() => process.env.EXPO_PUBLIC_AUTH_USE_MOCK === "true" ? createMockAuthGateway() : createConfiguredAuthGateway(getDeviceId), []);
  const [screen, setScreen] = useState<Screen>(recoveryReviewStep ? "forgotPassword" : "signIn"); const [email, setEmail] = useState(""); const [otp, setOtp] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [attemptId, setAttemptId] = useState(""); const [resendAt, setResendAt] = useState(0); const [seconds, setSeconds] = useState(0); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [submitting, setSubmitting] = useState(false); const [showPassword, setShowPassword] = useState(false); const [showConfirm, setShowConfirm] = useState(false);
  useEffect(() => { if (fontsLoaded || fontError) return; const timeout = setTimeout(() => setFontTimedOut(true), FONT_STARTUP_TIMEOUT_MS); return () => clearTimeout(timeout); }, [fontsLoaded, fontError]);
  useEffect(() => { const diagnostic = getFontStartupDiagnostic(fontError, fontTimedOut, isDebugBuild); if (diagnostic) console.warn(diagnostic); }, [fontError, fontTimedOut]);
  useEffect(() => { const update = () => setSeconds(Math.max(0, Math.ceil((resendAt - Date.now()) / 1000))); update(); const timer = setInterval(update, 1000); return () => clearInterval(timer); }, [resendAt]);
  const clearSensitive = () => { setOtp(""); setPassword(""); setConfirm(""); setShowPassword(false); setShowConfirm(false); };
  const go = (next: Screen) => { setError(""); setNotice(""); setScreen(next); };
  const sendOtp = async () => { const invalid = validateEmail(email); if (invalid) return setError(invalid); setSubmitting(true); try { const result = await gateway.requestOtp(normalizeEmail(email)); setEmail(normalizeEmail(email)); setAttemptId(result.attemptId); setResendAt(result.resendAvailableAt); go("signUpOtp"); } catch (cause) { setError(message(cause, "Không thể gửi mã.")); } finally { setSubmitting(false); } };
  const verify = async () => { if (!/^\d{6}$/.test(otp)) return setError("Nhập đủ 6 chữ số."); setSubmitting(true); try { await gateway.verifyOtp(email, attemptId, otp); go("signUpPassword"); } catch (cause) { setError(message(cause, "Không thể xác thực mã.")); } finally { setSubmitting(false); } };
  const resend = async () => { if (seconds || submitting) return; setSubmitting(true); try { const result = await gateway.resendOtp(email); setOtp(""); setAttemptId(result.attemptId); setResendAt(result.resendAvailableAt); } catch (cause) { setError(message(cause, "Không thể gửi lại mã.")); } finally { setSubmitting(false); } };
  const register = async () => { const invalid = validatePassword(password); if (invalid) return setError(invalid); if (password !== confirm) return setError("Xác nhận mật khẩu chưa khớp."); setSubmitting(true); try { await gateway.createAccount(email, attemptId, otp, password); clearSensitive(); go("signIn"); setNotice("Đăng ký thành công. Hãy đăng nhập để tiếp tục."); } catch (cause) { setError(message(cause, "Không thể tạo tài khoản.")); } finally { setSubmitting(false); } };
  const login = async () => { const invalid = validateEmail(email); if (invalid) return setError(invalid); if (!password) return setError("Nhập mật khẩu để đăng nhập."); if (submitting) return; setSubmitting(true); try { const session = await gateway.signIn(normalizeEmail(email), password); await gateway.me(session.accessToken); await signIn(session); clearSensitive(); } catch (cause) { if (cause instanceof GatewayError && cause.code === "ACCOUNT_UNVERIFIED") { try { const result = await gateway.requestOtp(normalizeEmail(email)); clearSensitive(); setAttemptId(result.attemptId); setResendAt(result.resendAvailableAt); go("signUpOtp"); setError(message(cause, "")); } catch (requestCause) { setError(message(requestCause, "Không thể gửi mã.")); } } else setError(message(cause, "Không thể đăng nhập.")); } finally { setSubmitting(false); } };
  const signUp = screen === "signUpEmail" || screen === "signUpOtp" || screen === "signUpPassword"; const formWidth = width < 400 ? Math.min(290, width - 40) : Math.min(320, width - 96); const submit = screen === "signUpEmail" ? sendOtp : screen === "signUpOtp" ? verify : screen === "signUpPassword" ? register : login;
  const fontStartup = getFontStartupState(fontsLoaded, fontError, fontTimedOut);
  if (fontStartup === "loading") return <StartupLoading />;
  if (screen === "forgotPassword") return <ForgotPasswordScreen gateway={gateway} initialStep={recoveryReviewStep ?? "email"} onExit={() => go("signIn")} onComplete={(recoveredEmail) => { clearSensitive(); setEmail(recoveredEmail); go("signIn"); setNotice("Đổi mật khẩu thành công. Hãy đăng nhập lại."); }} />;
  return <View style={styles.backdrop}><SafeAreaView style={[styles.canvas, { width: Math.min(width, 430) }]}><ScrollView contentContainerStyle={[styles.content, { paddingTop: height < 650 ? 24 : 72 }]} keyboardShouldPersistTaps="handled"><View style={[styles.header, height < 650 && styles.compactHeader]}><Text style={styles.title}>{signUp ? "Đăng ký" : "SmartTrọ\nxin chào!"}</Text></View><View style={[styles.form, { width: formWidth }, height < 650 && styles.compactForm]}>
    {(screen === "signIn" || screen === "signUpEmail") && <Input label="Email" value={email} onChangeText={setEmail} type="email-address" />}
    {screen === "signIn" && <SecretInput label="Mật khẩu" value={password} onChangeText={setPassword} visible={showPassword} onToggle={() => setShowPassword(!showPassword)} />}
    {screen === "signUpOtp" && <><Text style={styles.helper}>Nhập mã 6 chữ số đã gửi tới {maskedEmail(email)}</Text><Input label="Mã OTP" value={otp} onChangeText={(value) => setOtp(value.replace(/\D/g, "").slice(0, 6))} type="numeric" /></>}
    {screen === "signUpPassword" && <><Text style={styles.helper}>Tối thiểu 8 ký tự, gồm chữ hoa, số và ký tự đặc biệt.</Text><SecretInput label="Mật khẩu" value={password} onChangeText={setPassword} visible={showPassword} onToggle={() => setShowPassword(!showPassword)} /><SecretInput label="Nhập lại mật khẩu" value={confirm} onChangeText={setConfirm} visible={showConfirm} onToggle={() => setShowConfirm(!showConfirm)} /></>}
    {!!error && <Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text>}{!!notice && <Text accessibilityLiveRegion="polite" style={styles.notice}>{notice}</Text>}
    {screen === "signUpOtp" && <Action label={seconds ? `Gửi lại mã OTP (${seconds}s)` : "Gửi lại mã OTP"} disabled={!!seconds || submitting} onPress={() => void resend()} />}
    <Action label={submitting ? "Đang xử lý..." : screen === "signUpEmail" ? "Gửi OTP" : screen === "signUpOtp" ? "Tiếp tục" : signUp ? "Đăng ký" : "Đăng nhập"} disabled={submitting || (screen === "signUpOtp" && otp.length !== 6)} onPress={() => void submit()} /><Text style={styles.or}>Hoặc</Text>
    {showSocials && <Socials action={signUp ? "Đăng ký" : "Đăng nhập"} onPress={() => setNotice("Chức năng chưa khả dụng trong bản preview")} />}
    {screen === "signIn" && <Link label="Quên mật khẩu" onPress={() => { if (!showRecoveryReview) return setError("Quên mật khẩu chưa khả dụng trên bản production."); clearSensitive(); go("forgotPassword"); }} />}
    <Text style={styles.account}>{signUp ? "Bạn đã có tài khoản?" : "Bạn chưa có tài khoản?"}</Text><Link label={signUp ? "Đăng nhập" : "Đăng ký"} onPress={() => { clearSensitive(); go(signUp ? "signIn" : "signUpEmail"); }} />
  </View>{isDebugBuild && <Text style={styles.revision}>Preview revision: {process.env.EXPO_PUBLIC_BUILD_SHA?.slice(0, 7) ?? "local"}</Text>}</ScrollView></SafeAreaView></View>;
}
function StartupLoading() { return <View style={styles.startup}><Text style={styles.startupTitle}>SmartTrọ</Text><Text style={styles.startupCopy}>Preparing your secure sign in...</Text></View>; }
function Input({ label, value, onChangeText, type = "default" }: { label: string; value: string; onChangeText: (value: string) => void; type?: "default" | "email-address" | "numeric" }) { return <TextInput accessibilityLabel={label} autoCapitalize="none" autoCorrect={false} keyboardType={type} onChangeText={onChangeText} placeholder={label} placeholderTextColor="#A78B68" style={styles.input} value={value} />; }
function SecretInput({ label, value, onChangeText, visible, onToggle }: { label: string; value: string; onChangeText: (value: string) => void; visible: boolean; onToggle: () => void }) { return <View style={styles.secret}><TextInput accessibilityLabel={label} autoCapitalize="none" onChangeText={onChangeText} placeholder={label} placeholderTextColor="#A78B68" secureTextEntry={!visible} style={styles.secretInput} value={value} /><Pressable accessibilityLabel={visible ? "Ẩn mật khẩu" : "Hiện mật khẩu"} onPress={onToggle} style={styles.eye}><FontAwesome color="#A84300" name={visible ? "eye-slash" : "eye"} size={17} /></Pressable></View>; }
function Action({ label, onPress, disabled = false }: { label: string; onPress: () => void; disabled?: boolean }) { return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[styles.action, disabled && styles.disabled]}><Text style={styles.actionText}>{label}</Text></Pressable>; }
function Link({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={styles.link}><Text style={styles.linkText}>{label}</Text></Pressable>; }
function Socials({ action, onPress }: { action: string; onPress: () => void }) { return <View style={styles.socials}>
  <SocialButton asset={require("../../assets/social/facebook.png")} backgroundColor="#1877F2" label={`${action} với Facebook`} onPress={onPress} />
  <SocialButton asset={require("../../assets/social/google.png")} backgroundColor="#FFFFFF" label={`${action} với Google`} onPress={onPress} textColor="#777777" />
  <Pressable accessibilityRole="button" onPress={onPress} style={[styles.social, styles.apple]}><FontAwesome color="#FFFFFF" name="apple" size={24} style={styles.icon} /><Text style={styles.socialText}>{action} với Apple</Text></Pressable>
</View>; }
function SocialButton({ asset, backgroundColor, label, onPress, textColor = "#FFFFFF" }: { asset: number; backgroundColor: string; label: string; onPress: () => void; textColor?: string }) { return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.social, { backgroundColor }]}><Image accessibilityIgnoresInvertColors source={asset} style={styles.brandIcon} /><Text style={[styles.socialText, { color: textColor }]}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ startup: { alignItems: "center", backgroundColor: "#FF9A05", flex: 1, justifyContent: "center", padding: 36 }, startupTitle: { color: "#FFFFFF", fontSize: 42, fontWeight: "700" }, startupCopy: { color: "#FFFFFF", fontSize: 16, marginTop: 12, textAlign: "center" }, backdrop: { alignItems: "center", backgroundColor: "#FF9A05", flex: 1 }, canvas: { backgroundColor: "#FF9A05", flex: 1 }, content: { alignItems: "center", flexGrow: 1, paddingBottom: 22 }, header: { alignItems: "center", justifyContent: "center", minHeight: 144, width: "100%" }, compactHeader: { minHeight: 112 }, title: { color: "#FFFFFF", fontFamily: "BeVietnamPro_600SemiBold", fontSize: 48, lineHeight: 71, textAlign: "center" }, form: { marginTop: 28 }, compactForm: { marginTop: 14 }, input: { backgroundColor: "#FBC97E", borderRadius: 24, color: "#5B4126", fontFamily: "BeVietnamPro_400Regular", fontSize: 15, height: 48, marginBottom: 16, paddingHorizontal: 28 }, secret: { backgroundColor: "#FBC97E", borderRadius: 24, height: 48, marginBottom: 16 }, secretInput: { color: "#5B4126", fontFamily: "BeVietnamPro_400Regular", fontSize: 15, height: 48, paddingHorizontal: 28, paddingRight: 54 }, eye: { height: 48, justifyContent: "center", position: "absolute", right: 18 }, action: { alignItems: "center", backgroundColor: "#FFFFFF", borderColor: "#1684F7", borderRadius: 9, borderWidth: 1.5, height: 48, justifyContent: "center", marginTop: 10 }, actionText: { color: "#F09200", fontFamily: "BeVietnamPro_600SemiBold", fontSize: 14 }, disabled: { opacity: 0.55 }, or: { alignSelf: "center", color: "#FFFFFF", fontFamily: "BeVietnamPro_600SemiBold", fontSize: 15, marginVertical: 8 }, socials: { gap: 8 }, social: { alignItems: "center", borderRadius: 10, flexDirection: "row", height: 54, justifyContent: "center" }, apple: { backgroundColor: "#000000" }, brandIcon: { height: 24, left: 16, position: "absolute", width: 24 }, icon: { left: 16, position: "absolute" }, socialText: { color: "#FFFFFF", fontFamily: "BeVietnamPro_600SemiBold", fontSize: 15 }, link: { alignItems: "center", justifyContent: "center", minHeight: 28 }, linkText: { color: "#FFFFFF", fontFamily: "BeVietnamPro_600SemiBold", fontSize: 12, textDecorationLine: "underline" }, account: { color: "#FFFFFF", fontFamily: "BeVietnamPro_400Regular", fontSize: 12, marginTop: 8, textAlign: "center" }, helper: { color: "#FFFFFF", fontFamily: "BeVietnamPro_400Regular", fontSize: 12, lineHeight: 18, marginBottom: 10, minHeight: 18, textAlign: "center" }, error: { color: "#8B1C1C", fontFamily: "BeVietnamPro_400Regular", fontSize: 12, marginBottom: 2, textAlign: "center" }, notice: { color: "#5B4126", fontFamily: "BeVietnamPro_400Regular", fontSize: 12, marginBottom: 2, textAlign: "center" }, revision: { color: "rgba(255,255,255,0.7)", fontSize: 10, marginTop: 18 } });
